### PR TITLE
Binary builds

### PR DESCRIPTION
**Pull request by genzgd**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

The existing feedstock only generates source packages that do not include the Cython optimizations.  This PR actually builds the Cython code.

Note that smithy did not add Python 11 support, for reasons I could not figure out.

### CODE REVIEW

**Comment by genzgd** [comment]
No idea why the "test" of the ARM builds are failing

**Comment by gforsyth** [comment]
Hey @genzgd -- thanks for putting this together.
I haven't built cythonized packages for osx-arm64, but it looks like the error is pointing to some kind of CPU mismatch with the M1/M2 architecture:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=766870&view=logs&j=15f8dc28-9f6f-5e3a-5b3c-2b169071e5be&t=63fa899e-c160-5185-75c4-c5fd30c90374&l=1034

**Comment by genzgd** [comment]
I haven't the faintest idea how to fix the OSX ARM builds.  There's just a "warning" about differing architectures, not sure if that's breaking the test.  Seems like something that needs to be fixed in the OSX_ARM script?

**Comment by jonashaag** [comment]
@conda-forge-admin, please rerender

**Comment by jonashaag** [comment]
You are missing `test: native_and_emulated` in `conda-forge.yml`

**Comment by jonashaag** [comment]
NB: Also add `linux-aarch64`?

**Comment by gforsyth** [comment]
@conda-forge-admin, please rerender

**Comment by genzgd** [comment]
Thanks for the updates!

**Comment by gforsyth** [comment]
Thanks for the pointers on the osx-arm64 builds @jonashaag !

And thanks for putting this together @genzgd !  

Going to merge this in -- we can add `linux-aarch64` in another PR.

**Comment by genzgd** [comment]
Unfortunately something didn't work right.  I still don't get the C libraries installed (at least on my Mac M1).

**Comment by jonashaag** [comment]
The package itself is ok but for some reason it's not being found

```
$ micromamba create -p /tmp/env conda-forge/osx-arm64::clickhouse-connect
critical libmamba The package "conda-forge/osx-arm64::clickhouse-connect" is not available for the specified platform
```

**Pull request merged**
